### ISSUE TITLE
Födelsedagskort - Delmoment 3: Katten kan dansa!

### ISSUE THREAD

**Issue by torandersson** [Kodcentrum/Scratch-uppgifter#1]
Jag fick väldigt många frågor på när man skulle vända katten, finns en knapp högre upp som man med fördel kan använda. 

Föreslår att texten görs tydligare.

**Comment by jonwarghed** [comment]
Vi får samma sak på denna, ska se om jag hinner fixa en pull request för denna.

**Comment by kodcentrumcollaborative** [comment]
Gör gärna det, och annars fixar jag när jag får det lite lugnare, den har behövt åtgärd länge. /Lisa

**Comment by kodcentrumcollaborative** [comment]
Fixed.
