### ISSUE TITLE
Imse vimse spindel (publicerad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#46]
Anpassa text och bilder till Scratch 3.0 gränssnitt https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/master/block2_imsevimsespindel  

Länk: Se hur nya 3.0-sidan kommer se ut på Kodboken (på dold sida): Eventuella ändringar som görs behöver läggas till som commit av Pull Request av admin innan syns: https://www.kodboken.se/start/skapa-berattelser/uppgifter-i-scratch/imse-vimse-spindel-30?chpt=0

**Comment by marioleed** [comment]
Lisa Munkdahl arbetar med denna.
