### ISSUE TITLE
Fotbollspel (Skapa Spel) (publicerad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#47]
Uppdatera text och bilder till Scratch 3.0 gränssnitt https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/master/block1_fotbollspel 

Länk till dold sida på Kodboken som live-feedar från denna uppgift i repo Scratchuppgifter-v3. (kräver commit av PR innan effekt på sidan.) https://www.kodboken.se/start/skapa-spel/uppgifter-i-scratch/fotbollsspel-30?chpt=0

**Comment by kodcentrumcollaborative** [comment]
@marioleed Hej Mario! hur går det med denna uppgift? Kommer du att kunna färdigställa denna? Vore varmt tacksam! :)

**Comment by marioleed** [comment]
@kodcentrumcollaborative Jag har skapat ett första "färdigt" utkast som är i master nu. Det behöver väl egentligen korrekturläsas, men också bör några av bilderna förminskas också. Kan göra klart det i helgen.

**Comment by kodcentrumcollaborative** [comment]
@marioleed Fantastiskt! Pinga mig när det är färdigt, så lägger jag upp det på Kodboken. (ser nu att jag är i fel repo och skriver dig, sorry. :)

**Comment by kodcentrumcollaborative** [comment]
@marioleed Jag har nu lagt upp Fotbollspelet live på Kodboken (Skapa Spel), om du vill ändra på bilderna lite så vore det toppen, men du ser förändringarna här: https://www.kodboken.se/start/skapa-spel/uppgifter-i-scratch/fotbollsspel?chpt=0

**Comment by marioleed** [comment]
@kodcentrumcollaborative Nu har jag ändrat bilderna och anser att denna är klar nu. Men får gärna testas av någon annan också =)
