### ISSUE TITLE
Följ Frukten (Koda i Skolan, Äventyr med X och Y) (publicerad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#55]
Anpassa text och bild till Scratch 3.0 gränssnitt https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/master/block1_foljfrukten

**Comment by SGenheden** [comment]
Påbörjat denna - men kommer inte kunna avslutas förrän Remix är tillgängligt i Scratch 3:
https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/feature-folj-frukten/block1_foljfrukten

**Comment by kodcentrumcollaborative** [comment]
Tack @SGenheden  för att du adopterar även denna uppgift! Varmt uppskattat!

**Comment by kodcentrumcollaborative** [comment]
ping @SGenheden flytta kortet till Under arbete även i projektet om du börjar köra igång. Tack!
