### ISSUE TITLE
Jakten på Nyckeln (Koda i Skolan, Äventyr med X och Y) (publicerad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#56]
Anpassa text och bild till Scratch 3.0 gränssnitt https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/master/block3_jaktenpanyckeln

**Comment by SGenheden** [comment]
Går inte att konvertera för tillfället då det i beta versionen av Scratch 3.0 ingår att spara projekt i eget konto och därmed heller inte att dela och remixa projekt.

**Comment by kodcentrumcollaborative** [comment]
@SGenheden Men själva instruktionen kan man uppdatera med skärmsdumpsbilder tänker jag... För att komma framåt. Man kan ladda upp 2.0-projekt i Scratch Beta 3.0 lokalt från datorn. Men jag kanske helt missar din tanke här..?

**Comment by SGenheden** [comment]
Jo man kan absolut börja. Bara det att uppgiften inte går att göra klart förrän de släpper funktionaliteten att remixa projekt.

**Comment by kottkrig** [comment]
Vet vi något om när remix kan tänkas komma? Är det tänkt att vara med vid release?

Vi sågs i helgen ett gäng här i Göteborg och då böjade jag att ta skärmdumpar och gå igenom Jakten på nyckeln. Som du säger @SGenheden så går det ju inte att remixa projekt än men det var ganska smidigt att ladda upp en befintlig sprajt. Jag funderar på om en framkomlig väg är att skapa sprajter för exempelvis koordinatsystemet som läsaren kan ladda hem och sedan ladda upp till sitt projekt.

Vad tror ni?

**Comment by SGenheden** [comment]
Den 2:a januari kommer Scratch 3.0 studion ha tillgång till community-grejorna på scratch.mit.edu, dvs dagen för lansering. Som jag förstår det så finns det därför ingen anledning att köra om startprojektet, de ska kunna gå och remixas med Scratch 3.0 studion.

Jag är inte helt såld på att ha bilder någonstans som barnen måste ladda in  sina projekt. Det är lätt att de hamnar lite fel i x,y-läge och/eller att de hamnar över befintliga sprajter. Jag tror det var en av motivationen jag hade när jag skrev uppgiften. 

Jag föreslår att du gör om alla bilderna förutom de som visar på hur man remixar projektet - så fixar vi dem i januari (illa kvickt)

**Comment by kottkrig** [comment]
> Jag är inte helt såld på att ha bilder någonstans som barnen måste ladda in sina projekt. Det är lätt att de hamnar lite fel i x,y-läge och/eller att de hamnar över befintliga sprajter. Jag tror det var en av motivationen jag hade när jag skrev uppgiften.

Håller med. Men i det här fallet innebär det att ladda hem hela sprajten där vi också har möjlighet att lägga till kod som sätter bildens position till `x=0, y=0`.

Men om det är så att remix av projekt kommer med från dag 1 så kör vi såklart på det. 👍
