### ISSUE TITLE
Jakten på nyckeln PRO (Koda i Skolan, Äventyr med X och Y) (publiserad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#57]
Anpassa text och bild till Scratch 3.0 gränssnitt https://www.kodboken.se/start/kodaiskolan/aventyrxy/uppgifter-i-scratch/jakten-pa-nyckeln-pro?chpt=0

**Comment by kodcentrumcollaborative** [comment]
Hejja @Chrisse23 !! :)

**Comment by kodcentrumcollaborative** [comment]
Hejsan @Chrisse23 , hur ser status ut på denna uppgift? Bara så jag vet lite om ungefär när den kan tänkas komma upp. Synd vi inte sågs i Götet i veckan, nästa gång. Hälsningar//Jessica

**Comment by Chrisse23** [comment]
Hej! Den blir nog klar i helgen! Ja, synd att jag skulle bli sjuk just då! Hälsningar //Christoffer

**Comment by kodcentrumcollaborative** [comment]
Hejsan @Chrisse23 Comittade din PR, men har bara kollat det allra snabbaste - ser jättefint ut! Är det färdigt och good to go live på Kodboken anser du? Och Stort TACK!

**Comment by kodcentrumcollaborative** [comment]
Då lajvar jag den!
