### ISSUE TITLE
Matvinnaren Intro (Koda i Skolan, Matvinnaren) (publicerad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#59]
Anpassa text och bild till Scratch 3.0 gränssnitt https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/master/block4_matvinnare_intro

**Comment by SGenheden** [comment]
Påbörjat denna - men kommer inte kunna avslutas förrän Remix är tillgängligt i Scratch 3

**Comment by kodcentrumcollaborative** [comment]
Supertack @SGenheden  för arbetet du gör! Så uppskattat, du anar inte! Matvinnaren - så viktigt för skolan!

**Comment by kodcentrumcollaborative** [comment]
ping @SGenheden flytta kortet till Under arbete även i projektet om du börjar köra igång. Tack!

**Comment by kodcentrumcollaborative** [comment]
👍
