### ISSUE TITLE
Fruktsallad (Skapa Spel)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#72]
Anpassa text och bild till Scratch 3.0 gränssnitt https://www.kodboken.se/start/skapa-spel/uppgifter-i-scratch/fruktsallad?chpt=0 
Beslut att ej uppdatera denna instruktion och avpublicerad på kodboken.

**Comment by SGenheden** [comment]
Jag föreslår att vi stänger denna issue och tar bort uppgiften från kodboken.

**Comment by kodcentrumcollaborative** [comment]
jag instämmer! Är sedan en tid avpublicerad. Fixar @SGenheden
