### ISSUE TITLE
Kom igång: Villkor (Kom igång) (publiserad)

### ISSUE THREAD

**Issue by kodcentrumcollaborative** [Kodcentrum/Scratch-uppgifter#75]
Anpassa text och bild till Scratch 3.0 gränssnitt https://github.com/Kodcentrum/Scratchuppgifter-v3/tree/master/block1_grunderna3_om_satser

**Comment by SGenheden** [comment]
Går inte att konvertera för tillfället då det i beta versionen av Scratch 3.0 inte går att spara projekt i eget konto och därmed heller inte att dela och remixa projekt.

**Comment by kodcentrumcollaborative** [comment]
@andreascmj jag lade helt aktivitstiskt dig som ägare av de tre introducerande scratch-uppgifterna, kommer du att kunna uppdatera dem för anpassning till Scratch 3.0 innan nyår (helst...) ? Det skulle vara fantastiskt fint! Bara så jag vet om du ska ligga kvar. :)

**Comment by kodcentrumcollaborative** [comment]
Hej @andreascmj - hur går det med denna uppgift? Hoppas få den klar, då skolor efterfrågar den... :)

**Comment by kodcentrumcollaborative** [comment]
@andreascmj Supernyggt jobbat! TACK! Ställde fråga till dig på Slack även kring den "gamla" bilden som ligger kvar i din uppdatering (liten och svår att läsa, och sticker ut som äldre..) samt lade till en robot-intro-bild på förstasidan för att ge mer visuellt där, ändra om du misstycker.

**Comment by kodcentrumcollaborative** [comment]
Tack för fix @andreascmj ! Snyggt!
